In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import re
import time
import json
import pandas as pd
import numpy as np

# 頁碼(無隱藏)

In [2]:
web = webdriver.Chrome()
# base = 'https://paela-iecosystem.meida.tw/'
base = 'http://localhost:8081/'
# url = 'https://paela-iecosystem.meida.tw/#/intimacy-4-2'

Role = ['#/unintended-2', '#/youngdad-2', '#/daughter-2']
# ]
zh = ['我意外懷孕了', '我女友懷孕了', '我女兒懷孕了']
# ]我意外懷孕了

string = []
# 角色
for i, j in enumerate(Role) :
    url = base + j
    web.get(url)
    time.sleep(1)
    page = web.page_source
    Soup = BeautifulSoup(page,"lxml")
    State1 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > a")
    State11 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > p")
    # 第一層
    for k, l in enumerate(State1):
        Option1 = State1[k]['href']
        url = base + Option1
        web.get(url)
        time.sleep(1)
        page = web.page_source
        Soup = BeautifulSoup(page,"lxml")
        State2 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > a")
        State22 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > p")
        # 第二層
        for m, n in enumerate(State2):
            Option2 = State2[m]['href']
            url = base + Option2
            web.get(url)
            time.sleep(1)
            page = web.page_source
            Soup = BeautifulSoup(page,"lxml")
            State3 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > a")
            State33 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > p")
            if State3 == []:
                str0 = Role[i] + ',' + zh[i] + ',' +  \
                        State1[k]['href'] + ',' + State1[k].text + ',' + State11[k].text + ',' + \
                        State2[m]['href'] + ',' + State2[m].text + ',' + State22[m].text + ',,,,,,,,,'
                string.append(str0)
            else:
                # 第三層
                for o, p in enumerate(State3):
                    Option3 = State3[o]['href']
                    url = base + Option3
                    web.get(url)
                    time.sleep(1)
                    page = web.page_source
                    Soup = BeautifulSoup(page,"lxml")
                    State4 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > a")
                    State44 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > p")
                    if State4 == []:
                        str0 = Role[i] + ',' + zh[i] + ',' +  \
                                State1[k]['href'] + ',' + State1[k].text + ',' + State11[k].text + ',' + \
                                State2[m]['href'] + ',' + State2[m].text + ',' + State22[m].text + ',' + \
                                State3[o]['href'] + ',' + State3[o].text + ',' + State33[o].text + ',,,,,, '
                        string.append(str0)
                    else:
                        # 第四層
                        for s, t in enumerate(State4):
                            Option4 = State4[s]['href']
                            url = base + Option4
                            web.get(url)
                            time.sleep(1)
                            page = web.page_source
                            Soup = BeautifulSoup(page,"lxml")
                            State5 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > a")
                            State55 = Soup.select("ul.step-menu > li.aos-init:not(.d-none) > p")
                            if State5 == []:
                                str0 = Role[i] + ',' + zh[i] + ',' +  \
                                    State1[k]['href'] + ',' + State1[k].text + ',' + State11[k].text + ',' + \
                                    State2[m]['href'] + ',' + State2[m].text + ',' + State22[m].text + ',' + \
                                    State3[o]['href'] + ',' + State3[o].text + ',' + State33[o].text + ',' + \
                                    State4[s]['href'] + ',' + State4[s].text + ',' + State44[s].text +',,,'
                                string.append(str0)
                            else:
                                for r, q in enumerate(State5):
                                    str0 = Role[i] + ',' + zh[i] + ',' +  \
                                        State1[k]['href'] + ',' + State1[k].text + ',' + State11[k].text + ',' + \
                                        State2[m]['href'] + ',' + State2[m].text + ',' + State22[m].text + ',' + \
                                        State3[o]['href'] + ',' + State3[o].text + ',' + State33[o].text + ',' + \
                                        State4[s]['href'] + ',' + State4[s].text + ',' + State44[s].text + ',' + \
                                        State5[r]['href'] + ',' + State5[r].text + ',' + State55[r].text
                                    string.append(str0)

In [3]:
A = pd.DataFrame(string)
A[['Role', 'zh', 
    'Option1', 'Title1', 'Content1' ,
    'Option2', 'Title2', 'Content2' ,
    'Option3', 'Title3', 'Content3' ,
    'Option4', 'Title4', 'Content4' ,
    'Option5', 'Title5', 'Content5']] = A[0].str.split(",", expand=True)
A.drop(columns=0, inplace=True)

In [4]:
A.to_excel(r'小蝴蝶頁碼All_0323.xlsx', index=False)

# 內容

In [5]:
data = pd.read_excel(r'0321\小蝴蝶尾頁頁碼_0321v2.xlsx')

In [6]:
web = webdriver.Chrome()
# base = 'https://paela-iecosystem.meida.tw/#/'
base = 'http://localhost:8081/'
for i in range(len(data)):
    url = base + data.iloc[i, 0]
    web.get(url)
    time.sleep(2)
    page = web.page_source
    

    Soup = BeautifulSoup(page,"lxml")
    # Content = Soup.select("#\#app > div > div:nth-child(2) > div:nth-child(7) > main > section.container.step-rwd > div > div.container.step-box > div > div.select-menu > ul ")
    # data.iloc[i, 1] = str(Content)

    Content = Soup.select("#\#app > div > div:nth-child(2) > div:nth-child(7) > main > section.container.step-rwd > div > div.container.step-box > div > div.select-menu > ul > li ")
    data.iloc[i, 1] = str(Content)
web.close()

In [7]:
# data.to_excel(r'0321\小蝴蝶尾頁內容_0321v2.xlsx', index=False)

# ID

In [96]:
A = pd.DataFrame(string)
A[['Role', 'zh', 
    'Option1', 'Title1', 'Content1' ,
    'Option2', 'Title2', 'Content2' ,
    'Option3', 'Title3', 'Content3' ,
    'Option4', 'Title4', 'Content4' ,
    'Option5', 'Title5', 'Content5']] = A[0].str.split(",", expand=True)
A.drop(columns=0, inplace=True)
A.Role = A.Role.str.replace('#/', '')
A.Option1 = A.Option1.str.replace('#/', '')
A.Option2 = A.Option2.str.replace('#/', '')
A.Option3 = A.Option3.str.replace('#/', '')
A.Option4 = A.Option4.str.replace('#/', '')
A.Option5 = A.Option5.str.replace('#/', '')

In [97]:
ID_Table = pd.DataFrame()
ID_Table = pd.concat([ID_Table, A['Role']], axis=0)
ID_Table = pd.concat([ID_Table, A['Option1']], axis=0)
ID_Table = pd.concat([ID_Table, A['Option2']], axis=0)
ID_Table = pd.concat([ID_Table, A['Option3']], axis=0)
ID_Table = pd.concat([ID_Table, A['Option4']], axis=0)
ID_Table = pd.concat([ID_Table, A['Option5']], axis=0)
ID_Table = ID_Table.drop_duplicates()
# 排除空格
# ID_Table = ID_Table[ID_Table[0] != ' ']
# ID_Table = ID_Table.drop_duplicates()

ID_Table.reset_index(drop=True, inplace=True)
ID_Table.reset_index(inplace=True)
ID_Table.rename(columns={0:'ID_key', 'index':'ID'}, inplace=True)
# ID_Table.to_excel(r'ID_Table.xlsx', index=False)

c:\Users\cmuh1\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py:6242: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  diff = Index(subset).difference(self.columns)

Connect SQL

In [116]:
import pymysql

In [117]:
#連到SQL伺服器
db = pymysql.connect(host="127.0.0.1",user="root",\
        password="phpstudent", database="aragaki_yui", port=3306, charset="utf8")
cursor = db.cursor()#暫存區

In [118]:
#新增SQL表單
sql="CREATE TABLE IF NOT EXISTS `id_table`( \
    `id` INT UNSIGNED AUTO_INCREMENT, \
    `address` VARCHAR(50) NOT NULL, \
    `Content` VARCHAR(5000), \
    PRIMARY KEY ( `id` ))ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;"
cursor.execute(sql)
db.commit()

In [119]:
# 新增資料、檢查
for j in range(len(ID_Table)):
    sql = "select * from id_table where address='{}'".format(ID_Table.iloc[j, 1])
    cursor.execute(sql)
    db.commit()
    if cursor.fetchone() == None:#如果資料不存在插入
        address = ID_Table.iloc[j, 1]
        sql1 = "insert into id_table(address) values('{}')".format(address)
        cursor.execute(sql1)
        db.commit()
    else :
        print("資料已存在")

In [128]:
sql1

'UPDATE id_table SET Content = \'[<li class="aos-init" data-aos="fade-up"><h3>【女人想想】有限資源與無限韌性 青少年父母的茁壯路<br/> 陳美伶 發佈於 8 月 8, 2019</h3><p class="mb-20"> 文章來源： <a href="https://www.thinkingtaiwan.com/content/7790" target="_blank">https://www.thinkingtaiwan.com/content/7790</a><br/><br/></p><ul class="list mb-60"><li> 近兩年，出現好幾起未成年未婚懷孕生子或兒童被虐致死的社會案件新聞報導，大眾聽聞這樣的事件，輿論容易很快地以結果推論事實：因為新聞媒體的描述語句通常是「19歲大學生未婚產子扔垃圾桶」、「16歲少女廁所產子險溺斃」、「孩子疑似受到青少女母親的同居人虐待導致身上多處傷痕」，或是下個聳動標題；而大眾則容易以日常所聽到的、新聞所描述的片段訊息來拼湊對青少女母親的生活故事與全貌，卻忽視了到底是什麼樣的社會情境脈絡，導致青少女懷孕卻不敢主動求助？ </li><li> 有人真正關心這位當事人為什麼會懷孕嗎？為什麼「選擇」生下孩子？為了將孩子留在身邊做了什麼樣的努力？</li><li> 我們明瞭這些看似公義的評論，其實對這群青少女母親造成更多的汙名和標籤。她們為孩子所做的努力將再次被掩蓋，反而需要花更多力氣向他人證明自己的努力，才能由負轉正，才能獲得他人認同是個合格的好母親。事實上，他們如何在有限的條件下保持韌性地生活，社會大眾幾乎是無從得知的。 </li><li><h3>從懷孕到生產至養育 選擇難題與挑戰環環相扣</h3></li><li> 青少女懷孕服務方案歷經近十年的在地耕耘，看見一個青少女從確認自己懷孕到生產、留養的過程中所經歷的掙扎與矛盾，各個決定之間環環相扣。是否生產並非簡單的要或不要的個人意願選擇題，而是關聯著一段情感與關係的維持；或是受限法律規定而無法取得合法的墮胎管道；亦或考量與等待男方的表態，在等待過程中，胎兒持續留在母體中成長，過了適合終止懷孕的手術時間，繼續妊娠成為唯一的選項。 </li><li> 即使過了生產這一關，接下來要面臨留下來自己養或不得不選擇出養的議題，涉及必須思考原生家庭的態度與支持程度、男方的態度與回應、對個人教育與生涯規劃發展的影響、非婚生子女的處遇、婚姻與新生兒照顧計畫等議題。在這當中，當事人的聲音可能被視為重要聲音，但也可能被淹沒在周遭重要他人的意見中。當事人的個人意願不見得被視為重要的參考，只能被動配合他人所討論出來的決定。因此當決定留養，也代表著女性的身分角色即將轉換，隨之而來的則是這個角色被賦予的「責任」──不論是否已準備好站上母親這個位置，甚至是在幾乎沒有親屬資源的情形下，仍堅持將孩子帶在身邊養育。 </li><li> 然而，社會與原生家庭對於父母的親職角色有所期待，更遑論是青少年父母。當青少年父母因照顧知識缺乏、育兒壓力高漲、親密關係衝突、支持系統不足或嬰幼兒身心發展較為遲緩，以致子女出現受照顧狀況不佳時，社會及原生家庭對青少年父母的譴責更加嚴厲。例如：「養不起還要生，小孩有這樣的父母好可憐喔」、「這個小孩沒爸爸喔？！」、「你才幾歲，小孩一定顧不好」、「當爸媽了還想要出去玩」、「小孩顧小孩，怎麼顧得好」等等。 </li></ul></li>]\' WHERE address = \'support-3-3\''

In [129]:
# 內容更新進去
SQL_Content = data.copy()
SQL_Content.尾頁 = SQL_Content.尾頁.str.replace('#/', '')
for j in range(len(SQL_Content)):
    Content = SQL_Content.iloc[j, 1]
    sql1 = "UPDATE id_table SET Content = '{}' WHERE address = '{}'".format(Content, SQL_Content.iloc[j, 0])
    cursor.execute(sql1)
    db.commit()

In [41]:
sql = "select * from id_table "
cursor.execute(sql)
db.commit()
SQL_id_table = pd.DataFrame(cursor.fetchall())
db.close()

In [42]:
SQL_id_table.rename(columns={0:'ID', 1:'ID_key'}, inplace=True)

角色

In [80]:
Role = A[['Role', 'zh']].drop_duplicates()
Role['ID_key'] = A['Role']
Role = pd.merge(Role, SQL_id_table, how='left', on=['ID_key'])
Role.drop(columns='ID_key', inplace=True)
Role.rename(columns={'Role':'address', 'zh':'title'}, inplace=True)
Role

        address   title  ID
0  unintended-2  我意外懷孕了   1
1    youngdad-2  我女友懷孕了   2
2    daughter-2  我女兒懷孕了   3

選擇1

In [81]:
Table1 = A[['Role', 'Option1', 'Title1', 'Content1']].drop_duplicates()
Table1['ID_key'] = A['Option1']
Table1 = pd.merge(Table1, SQL_id_table, how='left', on=['ID_key'])
Table1.drop(columns='ID_key', inplace=True)
Table1

,Role,Option1,Title1,Content1,ID
0,unintended-2,talking-3,我不知道該怎麼做,這裡可以打簡短文案，整體比較一致。,4
1,unintended-2,unintended-3-1,我想要生下來,這裡可以打簡短文案，整體比較一致。,5
2,unintended-2,unintended-3-1,我只能選擇生下來,這裡可以打簡短文案，整體比較一致。,5
3,unintended-2,unintended-3-2,我還沒準備好生下來,這裡可以打簡短文案，整體比較一致。,6
4,youngdad-2,youngdad-3-4,不知道女友有沒有懷孕,這裡可以打簡短文案，整體比較一致。,7
5,youngdad-2,unintended-3-2-1,我還沒準備好生下來,這裡可以打簡短文案，整體比較一致。,8
6,youngdad-2,unintended-3-3,我們只能選擇生下來,這裡可以打簡短文案，整體比較一致。,9
7,youngdad-2,unintended-3-3,我們想要生下來,這裡可以打簡短文案，整體比較一致。,9
8,daughter-2,talking-3-1-1,不知道有沒有懷孕,不知道女兒(孩子的女友)有沒有懷孕,10
9,daughter-2,unintended-3-1-2,想把孩子生下來,如果女兒（孩子的女友）要生下寶寶，接下來會面對什麼狀況？,11
10,daughter-2,unintended-3-2-2,還沒準備好生下來,我還沒準備好要讓女兒生下寶寶，還能怎麼辦？,12

選擇2

In [82]:
Table2 = A[['Option1', 'Option2', 'Title2', 'Content2']].drop_duplicates()
Table2['ID_key'] = A['Option2']
Table2 = pd.merge(Table2, SQL_id_table, how='left', on=['ID_key'])
Table2.drop(columns='ID_key', inplace=True)
Table2 = Table2[Table2.ID != 94]
Table2

,Option1,Option2,Title2,Content2,ID
0,talking-3,medical-3-1,醫療議題,這裡可以打簡短文案，整體比較一致。,13
1,talking-3,talking-4-1,法律議題,這裡可以打簡短文案，整體比較一致。,14
2,talking-3,familyRelation-3-1,家庭關係,這裡可以打簡短文案，整體比較一致。,15
3,talking-3,intimacy-3-1,親密關係,這裡可以打簡短文案，整體比較一致。,16
4,unintended-3-1,medical-3-2,醫療議題,這裡可以打簡短文案，整體比較一致。,17
5,unintended-3-1,act-4-2,法律議題,這裡可以打簡短文案，整體比較一致。,18
6,unintended-3-1,familyRelation-4-2,家庭關係,這裡可以打簡短文案，整體比較一致。,19
7,unintended-3-1,study-4-1,就學問題,這裡可以打簡短文案，整體比較一致。,20
8,unintended-3-1,heartTohearts-4-1,親密關係,這裡可以打簡短文案，整體比較一致。,21
9,unintended-3-1,mentalCare-4-1,身心照顧,這裡可以打簡短文案，整體比較一致。,22
10,unintended-3-1,parenting-4-1,育兒預備,這裡可以打簡短文案，整體比較一致。,23
11,unintended-3-1,economy-4-1,經濟需求,這裡可以打簡短文案，整體比較一致。,24
12,unintended-3-2,medical-4-6,醫療議題,這裡可以打簡短文案，整體比較一致。,25
13,unintended-3-2,act-3-1-2,法律議題,這裡可以打簡短文案，整體比較一致。,26
14,unintended-3-2,MentalCare-4-3,身心照顧,這裡可以打簡短文案，整體比較一致。,27
15,unintended-3-2,FamilyRelation-3-2,家庭關係,這裡可以打簡短文案，整體比較一致。,28
16,unintended-3-2,chat,我需要幫助,這裡可以打簡短文案，整體比較一致。,29
17,youngdad-3-4,youngdad-4-1,醫療議題,這裡可以打簡短文案，整體比較一致。,30
18,youngdad-3-4,youngdad-4-2,法律議題,這裡可以打簡短文案，整體比較一致。,31
19,youngdad-3-4,familyRelation-4-4,家庭關係,這裡可以打簡短文案，整體比較一致。,32
20,youngdad-3-4,intimacy-3-1,親密關係,這裡可以打簡短文案，整體比較一致。,16
21,unintended-3-2-1,medical-4-6,醫療議題,這裡可以打簡短文案，整體比較一致。,25
22,unintended-3-2-1,youngdad-4-2,法律議題,這裡可以打簡短文案，整體比較一致。,31
23,unintended-3-2-1,MentalCare-4-3-1,身心照顧,這裡可以打簡短文案，整體比較一致。,33
24,unintended-3-2-1,FamilyRelation-4-2-1,家庭關係,這裡可以打簡短文案，整體比較一致。,34
25,unintended-3-2-1,chat,我需要幫助,這裡可以打簡短文案，整體比較一致。,29
26,unintended-3-3,medical-3-2,醫療議題,這裡可以打簡短文案，整體比較一致。,17
27,unintended-3-3,act-4-4,法律議題,這裡可以打簡短文案，整體比較一致。,35
28,unintended-3-3,familyRelation-4-2,家庭關係,這裡可以打簡短文案，整體比較一致。,19
29,unintended-3-3,study-4-2,就學問題,這裡可以打簡短文案，整體比較一致。,36
30,unintended-3-3,heartTohearts-4-1-1,親密關係,這裡可以打簡短文案，整體比較一致。,37
31,unintended-3-3,mentalCare-4-2,身心照顧,這裡可以打簡短文案，整體比較一致。,38
32,unintended-3-3,parenting-4-2,育兒預備,這裡可以打簡短文案，整體比較一致。,39
33,unintended-3-3,economy-4-2,經濟需求,這裡可以打簡短文案，整體比較一致。,40
34,talking-3-1-1,medical-3-1-1,醫療議題,這裡可以打簡短文案，整體比較一致。,41
35,talking-3-1-1,act-3-1-1,法律議題,這裡可以打簡短文案，整體比較一致。,42
36,talking-3-1-1,familyRelation-3-1-1,家庭關係,這裡可以打簡短文案，整體比較一致。,43
37,unintended-3-1-2,medical-3-2-1,醫療議題,迎接新生命的到來，女兒和寶寶的健康都很重要，讓我們來看看可以怎麼準備？,44
38,unintended-3-1-2,act-4-2-1,法律議題,相信你現在有種種擔憂，這些都是很正常的，讓我們來看看相關法律規範吧！,45
39,unintended-3-1-2,familyRelation-4-2-2,家庭關係,和家人討論過，和懷孕的女兒討論過了嗎？,46
40,unintended-3-1-2,study-4-1-1,就學問題,如果女兒還在讀書，能得到什麼協助？,47
41,unintended-3-1-2,mentalCare-4-1-1,身心照顧,懷孕的歷程，除了生理的變化，心理也可能承擔極大的壓力和負擔，讓我們陪你聊聊吧！,48
42,unintended-3-1-2,economy-4-1-2,經濟需求,柴米油鹽醬醋茶？以前怎麼沒有想到要花這麼多錢？,49
43,unintended-3-2-2,chat,我需要幫助,這裡可以打簡短文案，整體比較一致。,29
44,unintended-3-2-2,medical-4-6-1,醫療議題,這裡可以打簡短文案，整體比較一致。,50
45,unintended-3-2-2,act-3-1-1,法律議題,這裡可以打簡短文案，整體比較一致。,42
46,unintended-3-2-2,MentalCare-4-1-1,身心照顧,這裡可以打簡短文案，整體比較一致。,51
47,unintended-3-2-2,FamilyRelation-3-2,家庭關係,這裡可以打簡短文案，整體比較一致。,28

選擇3

In [83]:
Table3 = A[['Option2', 'Option3', 'Title3', 'Content3']].drop_duplicates()
Table3['ID_key'] = A['Option3']
Table3 = pd.merge(Table3, SQL_id_table, how='left', on=['ID_key'])
Table3.drop(columns='ID_key', inplace=True)
Table3 = Table3[Table3.ID != 94]
Table3

,Option2,Option3,Title3,Content3,ID
0,medical-3-1,medical-4-1,我可以中止懷孕嗎？,可以中止懷孕嗎？一定要有家長幫我簽同意書嗎？我男友成年了可以幫我簽嗎？,52
1,medical-3-1,medical-4-7,可以買事後避孕藥嗎？,我可以去藥局買事後避孕藥嗎？,53
2,medical-3-1,act-3-1,未成年拿避孕藥會被通報？,未成年去婦產科診所就醫 或是拿事後避孕藥會被通報嗎？,54
3,medical-3-1,medical-4-8,如何驗孕 / 就醫,怎麼樣確定有沒有懷孕？,55
4,medical-3-1,medical-4-8,保險套戴反了,保險套戴反了、立刻翻過來， 這樣還會懷孕嗎？,55
...,...,...,...,...,...
116,medical-4-6-1,unintended-4-2,懷孕超過時間,女兒懷孕的週數已經超過24週了，該怎麼辦？,75
117,medical-4-6-1,medical-5-3,人工流產,,89
118,MentalCare-4-1-1,mentalCare-5-1,面對孩子懷孕,面對孩子的非預期懷孕，你可能有很多未知和恐懼的擔心，無論是哪一種情緒，這都是陪伴你迎接新生...,80
119,MentalCare-4-1-1,mentalCare-5-2,心理狀況,不論孕期或是產後，媽媽的心理狀況都不容忽視，需要家人和朋友給予關心與支持,81
120,MentalCare-4-1-1,mentalCare-5-3,流產後憂鬱,流產後，女兒看起來鬱鬱寡歡，該怎麼辦？,92

選擇4

In [84]:
Table4 = A[['Option3', 'Option4', 'Title4', 'Content4']].drop_duplicates()
Table4['ID_key'] = A['Option4']
Table4 = pd.merge(Table4, SQL_id_table, how='left', on=['ID_key'])
Table4.drop(columns='ID_key', inplace=True)
Table4 = Table4[Table4.ID != 94]
Table4

,Option3,Option4,Title4,Content4,ID
2,act-3-1,act-4-3,我未滿16歲,我才14歲，發生性行為後，好像懷孕了怎麼辦…,59
3,act-3-1,act-4-1,我未滿20歲,我已經19歲了，可以自己決定要不要生嗎？（112年修正成未滿18歲）,60
24,unintended-4-2,unintended-5-7,出養,這裡可以打簡短文案，整體比較一致。,107
25,unintended-4-2,unintended-6-4,寄養,這裡可以打簡短文案，整體比較一致。,108
54,act-5-4,unintended-5-8,出養,這裡可以打簡短文案，整體比較一致。,109
55,act-5-4,unintended-6-4-1,寄養,這裡可以打簡短文案，整體比較一致。,110

選擇5

In [85]:
Table5 = A[['Option4', 'Option5', 'Title5', 'Content5']].drop_duplicates()
Table5['ID_key'] = A['Option5']
Table5 = pd.merge(Table5, SQL_id_table, how='left', on=['ID_key'])
Table5.drop(columns='ID_key', inplace=True)
Table5 = Table5[Table5.ID != 94]
Table5

           Option4           Option5 Title5           Content5   ID
3   unintended-5-7    unintended-6-1  什麼是出養  這裡可以打簡短文案，整體比較一致。  111
4   unintended-5-7    unintended-6-2   法律規定  這裡可以打簡短文案，整體比較一致。  112
5   unintended-5-7    unintended-6-3   社福資源  這裡可以打簡短文案，整體比較一致。  113
8   unintended-5-8  unintended-6-1-1  什麼是出養  這裡可以打簡短文案，整體比較一致。  114
9   unintended-5-8  unintended-6-2-1   法律規定  這裡可以打簡短文案，整體比較一致。  115
10  unintended-5-8  unintended-6-3-1   社福資源  這裡可以打簡短文案，整體比較一致。  116

# Json

In [86]:
T0 = Role.groupby('address').apply(lambda x:x[['ID', 'address', 'title']].to_dict('r')).to_dict()
T1 = Table1.groupby('Role').apply(lambda x:x[['ID', 'Option1', 'Title1', 'Content1']].to_dict('r')).to_dict()
T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
T4 = Table4.groupby('Option3').apply(lambda x:x[['ID', 'Option4', 'Title4', 'Content4']].to_dict('r')).to_dict()
T5 = Table5.groupby('Option4').apply(lambda x:x[['ID', 'Option5', 'Title5', 'Content5']].to_dict('r')).to_dict()

C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T0 = Role.groupby('address').apply(lambda x:x[['ID', 'address', 'title']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T0 = Role.groupby('address').apply(lambda x:x[['ID', 'address', 'title']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T0 = Role.groupby('address').apply(lambda x:x[['ID', 'address', 'title']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:2: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T1 = Table1.groupby('Role').apply(lambda x:x[['ID', 'Option1', 'Title1', 'Content1']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:2: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T1 = Table1.groupby('Role').apply(lambda x:x[['ID', 'Option1', 'Title1', 'Content1']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:2: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T1 = Table1.groupby('Role').apply(lambda x:x[['ID', 'Option1', 'Title1', 'Content1']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:3: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T2 = Table2.groupby('Option1').apply(lambda x:x[['ID', 'Option2', 'Title2', 'Content2']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  T3 = Table3.groupby('Option2').apply(lambda x:x[['ID', 'Option3', 'Title3', 'Content3']].to_dict('r')).to_dict()
C:\Users\cmuh1\AppData\Local\Temp\ipykernel_19476\1475283437.py:4: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.

In [87]:
for i in T4:
    for k in T4[i]:
        if k['Option4'] in T5:
            k['Option5'] = T5[k['Option4']]

In [88]:
for i in T3:
    for k in T3[i]:
        if k['Option3'] in T4:
            k['Option4'] = T4[k['Option3']]

In [89]:
for i in T2:
    for k in T2[i]:
        if k['Option2'] in T3:
            k['Option3'] = T3[k['Option2']]

In [90]:
for i in T1:
    for k in T1[i]:
        if k['Option1'] in T2:
            k['Option2'] = T2[k['Option1']]

In [91]:
for i in T0:
    for k in T0[i]:
        if k['address'] in T1:
            k['Option1'] = T1[k['address']]

In [92]:
pd.DataFrame(T0).to_json(r'小蝴蝶測試FINally.json', force_ascii=False, orient='records')